(ecallmgr@bebop.five9.com)1> 16:54:45.569 [alert] exception: {badarg,[{ets,select,[ecallmgr_channels,[{{channel,'$1','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','$2','_','_','_','_','_','_'},[{'=:=','$1',{const,<<"847635624@192.168.1.195">>}}],['$2']}]],[]},{ecallmgr_fs_channel,node,1,[{file,"src/ecallmgr_fs_channel.erl"},{line,77}]},{ecallmgr_call_events,maybe_process_channel_destroy,3,[{file,"src/ecallmgr_call_events.erl"},{line,412}]},{ecallmgr_call_events,handle_info,2,[{file,"src/ecallmgr_call_events.erl"},{line,270}]},{gen_listener,handle_callback_info,2,[{file,"src/gen_listener.erl"},{line,567}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,604}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,249}]}]}
16:54:45.575 [error] gen_server <0.2333.0> terminated with reason: bad argument in call to ets:select(ecallmgr_channels, [{{channel,'$1','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','$2','_',...},...}]) in ecallmgr_fs_channel:node/1 line 77
16:54:45.576 [error] CRASH REPORT Process <0.2333.0> with 0 neighbours exited with reason: bad argument in call to ets:select(ecallmgr_channels, [{{channel,'$1','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','$2','_',...},...}]) in ecallmgr_fs_channel:node/1 line 77 in gen_server:terminate/6 line 744
16:54:45.576 [error] Supervisor ecallmgr_call_event_sup had child ecallmgr_call_events started with ecallmgr_call_events:start_link('freeswitch@fs002-dev.2600hz.com', <<"847635624@192.168.1.195">>) at <0.2333.0> exit with reason bad argument in call to ets:select(ecallmgr_channels, [{{channel,'$1','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','$2','_',...},...}]) in ecallmgr_fs_channel:node/1 line 77 in context child_terminated
16:55:05.728 [alert] exception: {badarg,[{ets,select,[ecallmgr_channels,[{{channel,'$1','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','$2','_','_','_','_','_','_'},[{'=:=','$1',{const,<<"1956927243@192.168.1.195">>}}],['$2']}]],[]},{ecallmgr_fs_channel,node,1,[{file,"src/ecallmgr_fs_channel.erl"},{line,77}]},{ecallmgr_call_events,maybe_process_channel_destroy,3,[{file,"src/ecallmgr_call_events.erl"},{line,412}]},{ecallmgr_call_events,handle_info,2,[{file,"src/ecallmgr_call_events.erl"},{line,270}]},{gen_listener,handle_callback_info,2,[{file,"src/gen_listener.erl"},{line,567}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,604}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,249}]}]}
16:55:05.742 [error] gen_server <0.2506.0> terminated with reason: bad argument in call to ets:select(ecallmgr_channels, [{{channel,'$1','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','$2','_',...},...}]) in ecallmgr_fs_channel:node/1 line 77
16:55:05.743 [error] CRASH REPORT Process <0.2506.0> with 0 neighbours exited with reason: bad argument in call to ets:select(ecallmgr_channels, [{{channel,'$1','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','$2','_',...},...}]) in ecallmgr_fs_channel:node/1 line 77 in gen_server:terminate/6 line 744
16:55:05.743 [error] Supervisor ecallmgr_call_event_sup had child ecallmgr_call_events started with ecallmgr_call_events:start_link('freeswitch@fs002-dev.2600hz.com', <<"1956927243@192.168.1.195">>) at <0.2506.0> exit with reason bad argument in call to ets:select(ecallmgr_channels, [{{channel,'$1','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','$2','_',...},...}]) in ecallmgr_fs_channel:node/1 line 77 in context child_terminated
16:56:10.568 [alert] exception: {badarg,[{ets,select,[ecallmgr_channels,[{{channel,'$1','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','$2','_','_','_','_','_','_'},[{'=:=','$1',{const,<<"418732107@192.168.1.195">>}}],['$2']}]],[]},{ecallmgr_fs_channel,node,1,[{file,"src/ecallmgr_fs_channel.erl"},{line,77}]},{ecallmgr_call_events,maybe_process_channel_destroy,3,[{file,"src/ecallmgr_call_events.erl"},{line,412}]},{ecallmgr_call_events,handle_info,2,[{file,"src/ecallmgr_call_events.erl"},{line,270}]},{gen_listener,handle_callback_info,2,[{file,"src/gen_listener.erl"},{line,567}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,604}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,249}]}]}
16:56:10.573 [error] gen_server <0.2758.0> terminated with reason: bad argument in call to ets:select(ecallmgr_channels, [{{channel,'$1','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','$2','_',...},...}]) in ecallmgr_fs_channel:node/1 line 77
16:56:10.573 [error] CRASH REPORT Process <0.2758.0> with 0 neighbours exited with reason: bad argument in call to ets:select(ecallmgr_channels, [{{channel,'$1','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','$2','_',...},...}]) in ecallmgr_fs_channel:node/1 line 77 in gen_server:terminate/6 line 744
16:56:10.574 [error] Supervisor ecallmgr_call_event_sup had child ecallmgr_call_events started with ecallmgr_call_events:start_link('freeswitch@fs002-dev.2600hz.com', <<"418732107@192.168.1.195">>) at <0.2758.0> exit with reason bad argument in call to ets:select(ecallmgr_channels, [{{channel,'$1','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','$2','_',...},...}]) in ecallmgr_fs_channel:node/1 line 77 in context child_terminated
16:57:27.667 [alert] exception: {badarg,[{ets,select,[ecallmgr_channels,[{{channel,'$1','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','$2','_','_','_','_','_','_'},[{'=:=','$1',{const,<<"1649697346@192.168.1.195">>}}],['$2']}]],[]},{ecallmgr_fs_channel,node,1,[{file,"src/ecallmgr_fs_channel.erl"},{line,77}]},{ecallmgr_call_events,maybe_process_channel_destroy,3,[{file,"src/ecallmgr_call_events.erl"},{line,412}]},{ecallmgr_call_events,handle_info,2,[{file,"src/ecallmgr_call_events.erl"},{line,270}]},{gen_listener,handle_callback_info,2,[{file,"src/gen_listener.erl"},{line,567}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,604}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,249}]}]}
16:57:27.672 [error] gen_server <0.3075.0> terminated with reason: bad argument in call to ets:select(ecallmgr_channels, [{{channel,'$1','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','$2','_',...},...}]) in ecallmgr_fs_channel:node/1 line 77
16:57:27.672 [error] CRASH REPORT Process <0.3075.0> with 0 neighbours exited with reason: bad argument in call to ets:select(ecallmgr_channels, [{{channel,'$1','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','$2','_',...},...}]) in ecallmgr_fs_channel:node/1 line 77 in gen_server:terminate/6 line 744
16:57:27.673 [error] Supervisor ecallmgr_call_event_sup had child ecallmgr_call_events started with ecallmgr_call_events:start_link('freeswitch@fs002-dev.2600hz.com', <<"1649697346@192.168.1.195">>) at <0.3075.0> exit with reason bad argument in call to ets:select(ecallmgr_channels, [{{channel,'$1','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','$2','_',...},...}]) in ecallmgr_fs_channel:node/1 line 77 in context child_terminated
16:59:45.577 [alert] exception: {badarg,[{ets,member,[ecallmgr_channels,<<"847635624@192.168.1.195">>],[]},{ecallmgr_fs_channel,exists,1,[{file,"src/ecallmgr_fs_channel.erl"},{line,109}]},{ecallmgr_call_events,handle_info,2,[{file,"src/ecallmgr_call_events.erl"},{line,346}]},{gen_listener,handle_callback_info,2,[{file,"src/gen_listener.erl"},{line,567}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,604}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,249}]}]}
16:59:45.581 [error] gen_server <0.2466.0> terminated with reason: bad argument in call to ets:member(ecallmgr_channels, <<"847635624@192.168.1.195">>) in ecallmgr_fs_channel:exists/1 line 109
16:59:45.581 [error] CRASH REPORT Process <0.2466.0> with 0 neighbours exited with reason: bad argument in call to ets:member(ecallmgr_channels, <<"847635624@192.168.1.195">>) in ecallmgr_fs_channel:exists/1 line 109 in gen_server:terminate/6 line 744
16:59:45.582 [error] Supervisor ecallmgr_call_event_sup had child ecallmgr_call_events started with ecallmgr_call_events:start_link('freeswitch@fs002-dev.2600hz.com', <<"847635624@192.168.1.195">>) at <0.2466.0> exit with reason bad argument in call to ets:member(ecallmgr_channels, <<"847635624@192.168.1.195">>) in ecallmgr_fs_channel:exists/1 line 109 in context child_terminated

