### Attachment Handlers Errors

Retrieve attachment handlers errors


#### List all the stored errors

> GET /v2/accounts/{ACCOUNT_ID}/att_handlers_errors

```shell
curl -v -X GET \
    -H "X-Auth-Token: {AUTH_TOKEN}" \
    http://{SERVER}:8000/v2/accounts/{ACCOUNT_ID}/att_handlers_errors
```
```json
{
  "page_size" : 5,
  "start_key" : "g24FANAHFtQO",
  "data" : [
    {
      "id" : "201803-586ce197ae32cfa5f16e94736f47fbd3",
      "attachment_name" : "99a81a3436ce569631a4f8e82f0afae0_test_credentials_file.txt",
      "resp_code" : 403,
      "reason" : "The AWS Access Key Id you provided does not exist in our records."
    },
    {
      "id" : "201803-586ce197ae32cfa5f16e94736f47ec5f",
      "attachment_name" : "18cdfa814a6451bff0604b86f0dc76f9_test_credentials_file.txt",
      "resp_code" : 403,
      "reason" : "The AWS Access Key Id you provided does not exist in our records."
    },
    {
      "id" : "201803-c371e3fdd10f5cdb88b1756e6ce0d877",
      "attachment_name" : "579a7ceb533bd63391ce5c035e626781_test_credentials_file.txt",
      "resp_code" : 403,
      "reason" : "The AWS Access Key Id you provided does not exist in our records."
    },
    {
      "id" : "201803-6d670f21a8184140cb31770959e09dbd",
      "attachment_name" : "01c5f64e1c8f14d1123cacf6921e43b4_test_credentials_file.txt",
      "resp_code" : 403,
      "reason" : "The AWS Access Key Id you provided does not exist in our records."
    },
    {
      "id" : "201803-461d4a97783105a46deb559e45d12266",
      "attachment_name" : "c669cd4df0cb57625a8634562dd994e6_test_credentials_file.txt",
      "resp_code" : 403,
      "reason" : "The AWS Access Key Id you provided does not exist in our records."
    }
  ],
  "revision" : "ef20ee5deff0a85f34e5c5555faa4903",
  "timestamp" : "2018-03-08T19:15:28",
  "version" : "4.3.1",
  "node" : "p1vlV1a_qodo9eHpALZAKw",
  "request_id" : "b70dbb60666e83a6316df8e0681fa417",
  "status" : "success",
  "auth_token" : "..."
}
```

#### Get all the information for a given stored error

> GET /v2/accounts/{ACCOUNT_ID}/att_handlers_errors/{ERROR_ID}

```shell
curl -v -X GET \
    -H "X-Auth-Token: {AUTH_TOKEN}" \
    http://{SERVER}:8000/v2/accounts/{ACCOUNT_ID}/att_handlers_errors/{ERROR_ID}
```
```json
{
  "data" : {
    "attachment_name" : "c669cd4df0cb57625a8634562dd994e6_test_credentials_file.txt",
    "db_name" : "account%2F67%2Fc6%2Fd3eb4b5f3486ac51dea16e8064a9-201803",
    "document_id" : "aeda8252cb95a4943d91c11d0fd1ac04",
    "handler_props" : {
      "bucket" : "my_S3_BUCKET",
      "key" : "my_AWS_ACCESS_KEY",
      "secret" : "my_AWS_SECRET_KEY"
    },
    "options" : {
      "rev" : "1-b9b24bdddc20aa1a8702a78b5f111406",
      "doc_type" : "storage_settings_probe",
      "error_verbosity" : "verbose"
    },
    "req_url" : "account%2F67%2Fc6%2Fd3eb4b5f3486ac51dea16e8064a9-201803/aeda8252cb95a4943d91c11d0fd1ac04_c669cd4df0cb57625a8634562dd994e6_test_credentials_file.txt",
    "resp_body" : "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>my_AWS_ACCESS_KEY</AWSAccessKeyId><RequestId>F9ABFC34EDBD7CF4</RequestId><HostId>v9p8GqEAolAyMc39sByE5hsDw9BQMbRxV0D6fajkCASWs5zTx0poP42AdlHTcRdojEkaOwLHjFM=</HostId></Error>",
    "resp_code" : 403,
    "handler_id" : "custom-handler-id",
    "reason" : "The AWS Access Key Id you provided does not exist in our records.",
    "id" : "201803-461d4a97783105a46deb559e45d12266"
  },
  "revision" : "1-1d947805e5c21477d094cbb678fdcaea",
  "timestamp" : "2018-03-08T19:18:37",
  "version" : "4.3.1",
  "node" : "p1vlV1a_qodo9eHpALZAKw",
  "request_id" : "c9e00eeeeb28508114697e0d1e7200b0",
  "status" : "success",
  "auth_token" : "..."
}
```

#### Get all the stored errors generated by the given handler-id

> GET /v2/accounts/{ACCOUNT_ID}/att_handlers_errors/handler/{HANDLER_ID}

```shell
curl -v -X GET \
    -H "X-Auth-Token: {AUTH_TOKEN}" \
    http://{SERVER}:8000/v2/accounts/{ACCOUNT_ID}/att_handlers_errors/handler/{HANDLER_ID}
```
```json
{
  "page_size" : 3,
  "start_key" : "g2wAAAACbQAAABFjdXN0b20taGFuZGxlci1pZG4FABgGFtQOag",
  "data" : [
    {
      "id" : "201803-c371e3fdd10f5cdb88b1756e6ce0d877",
      "attachment_name" : "579a7ceb533bd63391ce5c035e626781_test_credentials_file.txt",
      "resp_code" : 403,
      "reason" : "The AWS Access Key Id you provided does not exist in our records."
    },
    {
      "id" : "201803-6d670f21a8184140cb31770959e09dbd",
      "attachment_name" : "01c5f64e1c8f14d1123cacf6921e43b4_test_credentials_file.txt",
      "resp_code" : 403,
      "reason" : "The AWS Access Key Id you provided does not exist in our records."
    },
    {
      "id" : "201803-461d4a97783105a46deb559e45d12266",
      "attachment_name" : "c669cd4df0cb57625a8634562dd994e6_test_credentials_file.txt",
      "resp_code" : 403,
      "reason" : "The AWS Access Key Id you provided does not exist in our records."
    }
  ],
  "revision" : "7eebf3cd4c24826feeb59f9d59ab2493",
  "timestamp" : "2018-03-08T19:08:08",
  "version" : "4.3.1",
  "node" : "p1vlV1a_qodo9eHpALZAKw",
  "request_id" : "573f2d76601744af316f1e2fc24c9304",
  "status" : "success",
  "auth_token" : "..."
}
```

